version: "3"

services:
  redis:
    image: "redis:6-alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
  malwarepadfiles:
    build: ./
    env_file:
      - .env
    ports:
      - "9872:3000"
    restart: always
    tty: true
    depends_on:
      - redis
